name: 'Test'
on:
  # Disabled per this section https://github.com/Anthony-Fiddes/miryoku_babel/tree/master?tab=readme-ov-file#initial-setup-1
  # - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["test"]'
